# Generated by Django 5.0.4 on 2024-05-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0004_alter_dailypublicequitytrades_closing_bid_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailybillcodpapertrades",
            name="closing_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybillcodpapertrades",
            name="closing_yield",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybillcodpapertrades",
            name="day_high_yield",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybillcodpapertrades",
            name="day_low_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybillcodpapertrades",
            name="day_low_yeild",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybillcodpapertrades",
            name="opening_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybillcodpapertrades",
            name="opening_yield",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybondnotetrades",
            name="closing_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybondnotetrades",
            name="closing_yield",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybondnotetrades",
            name="day_high_yield",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybondnotetrades",
            name="day_low_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybondnotetrades",
            name="day_low_yeild",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybondnotetrades",
            name="opening_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailybondnotetrades",
            name="opening_yield",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailypublicequitytrades",
            name="closing_bid_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailypublicequitytrades",
            name="closing_offer_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailypublicequitytrades",
            name="closing_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailypublicequitytrades",
            name="last_transaction_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailypublicequitytrades",
            name="opening_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailypublicequitytrades",
            name="previous_closing_price",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailypublicequitytrades",
            name="price_change",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailypublicequitytrades",
            name="total_shares_traded",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailypublicequitytrades",
            name="total_value_traded",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailypublicequitytrades",
            name="year_high",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="dailypublicequitytrades",
            name="year_low",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
    ]
