# Generated by Django 5.1.7 on 2025-03-09 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticker",
            name="long_business_summary",
        ),
    ]
