# Generated by Django 5.1.7 on 2025-03-09 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_remove_ticker_long_business_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprice",
            name="adjusted_close",
        ),
    ]
