# Generated by Django 5.0.4 on 2024-05-08 19:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0002_client_inception_date_alter_account_inception_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("total_value", models.DecimalField(decimal_places=5, max_digits=15)),
                ("total_gain", models.DecimalField(decimal_places=5, max_digits=15)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("entity", "date", "advisor")},
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "market_value",
                    models.DecimalField(decimal_places=5, max_digits=15, null=True),
                ),
                ("quantity", models.DecimalField(decimal_places=5, max_digits=15)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.account"
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.security"
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "security", "date")},
            },
        ),
        migrations.CreateModel(
            name="SecurityPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=5, max_digits=15)),
                ("date", models.DateField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "securityid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.security"
                    ),
                ),
            ],
            options={
                "unique_together": {("securityid", "date")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("BUY", "buy"),
                            ("SELL", "sell"),
                            ("DEPOSIT", "deposit"),
                            ("WITHDRAWAL", "withdrawal"),
                            ("INSTRUMENT-CASHFLOW", "instrument-cashflow"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "transaction_quantity",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=15),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=5, max_digits=15),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z_]*$",
                                "Only alphanumeric characters are allowed.",
                            )
                        ],
                    ),
                ),
                ("comment", models.CharField(max_length=200)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.account"
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.security",
                    ),
                ),
            ],
            options={
                "unique_together": {("transaction_id",)},
            },
        ),
    ]
