# Generated by Django 5.0.4 on 2024-04-18 02:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clientid", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("date_opened", models.DateField()),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("CORPORATION", "Corporation"),
                            ("TRUST", "Trust"),
                            ("FOUNDATION", "Foundation"),
                        ],
                        default="INDIVIDUAL",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("clientid",)},
            },
        ),
        migrations.CreateModel(
            name="SecurityIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "security_industry",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "[A-Za-z]*$", "Only alphabetic characters are allowed."
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Industry",
                "verbose_name_plural": "Security Industries",
                "unique_together": {("security_industry",)},
            },
        ),
        migrations.CreateModel(
            name="SecuritySector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "security_sector",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "[A-Za-z]*$", "Only alphabetic characters are allowed."
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Sector",
                "verbose_name_plural": "Security Sectors",
                "unique_together": {("security_sector",)},
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accountid", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=50)),
                ("date_opened", models.DateField()),
                ("inception_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "clientid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.client"
                    ),
                ),
            ],
            options={
                "unique_together": {("accountid",)},
            },
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("securityid", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("isin", models.CharField(blank=True, max_length=50)),
                ("ticker", models.CharField(blank=True, max_length=50)),
                (
                    "unit_of_measure",
                    models.DecimalField(decimal_places=5, max_digits=15, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.securityindustry",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.securitysector",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Securities",
                "unique_together": {("securityid",)},
            },
        ),
    ]
