# Generated by Django 5.0.4 on 2024-05-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="inception_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="inception_date",
            field=models.DateField(null=True),
        ),
    ]
